version: "3.8"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: "./prometheus_config"
        target: /etc/prometheus

  server:
    image: node
    hostname: server
    command: ["/app/run.sh"]
    ports:
      - "9100:9100"
    volumes:
      - type: bind
        source: "./server"
        target: /app
